config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  get '/:locale', to: 'home#index'


  scope '/(:locale)', locale: /en|fr|pt/ do    
    get 'a2c', to: "reports#index"
    resources :reports, path: '/a2c/reports' do
      member do
        get :competitors
      end

      collection do
      end
      
      collection do
        post :save_similar_properties   , defaults: { format: :json }
      end
    end

    # for A2C service related api 
    get 'a2c/:action',controller: :a2c
    # API
    get 'a2c/evolution_price', to: 'a2c#evolution_price', 
      defaults: { locale: :en, format: :json }
    get 'a2c/search_properties', to: 'a2c#search_properties', 
      defaults: { locale: :en, format: :json }

    
  end



end

app/models/report.rb
class Report < ActiveRecord::Base
  paginates_per 20
  
  default_scope { order('created_at DESC') }
  
  has_and_belongs_to_many :similar_properties

  attr_accessor :image_json

  enum property_type: {house: 0,  flat: 1}

  before_validation :set_photo_base64
  after_save        :set_photo_path

  has_attached_file :photo, 
    styles: { 
      medium: "300x300>", 
      thumb: "100x100>" 
    }, 
    default_url: "/images/:style/missing.png"
    
  validates_attachment :photo, 
    content_type: 
    { 
      content_type: ["image/jpeg", "image/jpg", "image/png"] 
    }, size: { in: 0..10.megabytes }
  
  def set_photo_base64
    if image_json.present?
      image                   = Paperclip.io_adapters.for(image_json)
      extension               = image.content_type.split('/')[1]
      image.original_filename = "photo.#{extension}"
      self.photo              = image
    end
  end

  def set_photo_path
    if self.photo.present?
      self.photo_path = self.photo.url(:medium)
      self.update_column(:photo_path, self.photo.url(:medium))
    end
  end

end

app/models/similar_property.rb
class SimilarProperty < ActiveRecord::Base
  has_and_belongs_to_many :reports
end

app/controllers/a2c_controller.rb
class A2cController  < ApplicationController

  protect_from_forgery except: :evolution_price
  skip_before_action  :set_locale, only: [:evolution_price]

	# API 
	def stats
		data = {
			median_price: rand(1000),
			on_market_similar_props: rand(1000),
			sold_similar_props: rand(1000),			
		}
		render json:  data.to_json
	end

   def search_properties
      price   = params[:price].to_i
      surface = params[:surface].to_f
      city    = params[:city]

      # maybe futur param?
      price_margin = price * 0.10
      surface_margin = surface * 0.10

      # fake service
      observatory = ObservatoryService.new()    
      data = observatory.search(
      	price: price, 
        surface: surface, 
        city: city, 
        price_margin: price_margin, 
        surface_margin: surface_margin)

      render json: { properties: data }
  end

  def evolution_price 
    data = [{
      name: 'Tokyo',
      data: [10,9,8,7,6,5,4,3,2,1]
    }, {
      name: 'London',
      data: [1,2,3,4,5,6,7,8,9,10]
    }]
    render json: { data: data }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_locale
  protect_from_forgery with: :exception

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  def index
    @reports = has_search_params? ? filter_search : Report.all
    @reports = @reports.page(params[:page]) if @reports.any?
  end

  def show
    @report = @report.to_json(include: :similar_properties)
  end

  def new
    @report = Report.new
  end

  def edit
    @report = @report.to_json(include: :similar_properties)
  end

  def competitors
    @report = Report
      .find(params[:id])
      .to_json(include: :similar_properties)
      .html_safe 
  end


  def save_similar_properties
    properties = params[:properties]
    report = Report.find(params[:report_id])
    report.similar_properties.destroy_all
    if properties.present?
      properties.each do |property_id| 
        report.similar_properties << SimilarProperty.find(property_id)
      end
    end
    render json: { similars: report.similar_properties }, status: 200
  end

  def create
    base64 = params[:report].try(:[], :photo).try(:[], :src)
    @report = Report.new(report_params.merge(image_json: base64))
    respond_to do |format|
      if @report.save
        format.html { redirect_to competitors_report_path(@report) }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    base64 = params[:report].try(:[], :photo).try(:[], :src)
    respond_to do |format|
      if @report.update(report_params.merge(image_json: base64))
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render json: { report: @report }, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_report
    @report = Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:property_type,
                                   :photo,
                                   :rooms,
                                   :address,
                                   :surface,
                                   :price,
                                   :city,
                                   :description,
                                   :name,
                                   :phone,
                                   :email,
                                   :lat,
                                   :lng)
  end

  def filter_search
    name       = params[:contact_name]
    date_query = build_date_query

    if date_query.present? && name.present?
      date_query
        .where("name ILIKE ?", "%#{name}%")
    elsif date_query.nil? && name.present?
      Report
        .where("name ILIKE ?", "%#{name}%")
    elsif name.blank? && date_query.present?
      date_query
    else
      Report.all
    end

  end

  def build_date_query
    to_date     = parse_date(params[:to_date])
    from_date   = parse_date(params[:from_date])
    valid_dates = valid_dates?(from_date, to_date)
    # If just initial date, get results starting from
    if from_date.present? && to_date.nil?
      Report
        .where('created_at >= ?', from_date.beginning_of_day)
    # If just last date, get results until date    
    elsif from_date.nil? && to_date.present?
      Report
        .where('created_at <= ?', to_date.end_of_day)
    elsif valid_dates
      Report
        .where(created_at: range(from_date, to_date))
    end    
  end

  def range(from, to)
    (from.beginning_of_day)..(to.end_of_day)
  end

  def parse_date(date)
    DateTime.parse(date)
  rescue
    nil
  end

  def valid_dates?(from, to)
    from.present? && to.present? && from <= to
  end

  def has_search_params?
    params[:contact_name].present? || params[:to_date].present? || params[:from_date].present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/home/index.slim
 
h1
  A2C Service 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html moznomarginboxes mozdisallowselectionprint>
<head>
  <title>PrintReport</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  
  <!-- Custom CSS -->
  <%= stylesheet_link_tag    'style', media: 'all' %>
  <%= stylesheet_link_tag    'print', media: 'print' %>
  <!-- Bootstrap -->
  <%= stylesheet_link_tag    'vendor/bootstrap.min' %>
  <%= javascript_include_tag 'vendor/bootstrap.min' %>
  <!-- AngularJS -->
  <%= javascript_include_tag 'vendor/angular.min' %>
  <!-- External -->
  <link href='https://fonts.googleapis.com/css?family=Lato:400,100,300,700' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
<nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
  <%= link_to 'Print Report', root_path, class: 'navbar-brand' %>
   <ul class="nav navbar-nav">
    <li class="nav-item <%= 'active' if current_page?(reports_path) %>">
      <%= link_to t('reports'), reports_path, class: 'nav-link' %>
    </li>
  </ul>
  <ul class="nav navbar-nav pull-xs-right">
    <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Language</a>
    <div class="dropdown-menu">
      <%#= link_to "English"  , params.merge(locale: :en), class: 'dropdown-item' %>
      <%= link_to "Français" , params.merge(locale: :fr), class: 'dropdown-item' %>
      <%= link_to "Português", params.merge(locale: :pt), class: 'dropdown-item' %>
    </div>
    </li>
  </ul>
</nav>
<div class="container-fluid">
  <%= yield %>
</div>
</body>
</html>

app/views/reports/_form.slim
= content_for :head 
  = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyDWif-Vrje2gPVDFGFWcUytgJmZxUMQlRU&libraries=places"
  = javascript_include_tag 'address_complete'
  = javascript_include_tag 'views/properties/show'

= form_for(@report) do |f|
  - if @report.errors.any?
    #error_explanation
      h2
        = pluralize(@report.errors.count, "error")
        | prohibited this report from being saved:
      ul
        - @report.errors.full_messages.each do |message|
          li= message
  fieldset.form-group
    label = t('property_type')
    .radio
      label
        = f.radio_button :property_type, Report.property_types.keys[0]
        = t('house')
    .radio
      label
        = f.radio_button :property_type, Report.property_types.keys[1]
        = t('flat')

  fieldset.form-group
    label = t('photo')
    = f.file_field :photo, class: 'form-control-file'
  .form-group
    = f.label :rooms, t('rooms')
    = f.number_field :rooms, class: 'form-control'
  .form-group
    = f.label :description, t('description')
    = f.text_field :description, class: 'form-control'
  .form-group
    = f.label :address, t('address')
    = f.text_field :address, class: 'form-control', id: 'address_field'
  .form-group
    = f.label :surface, t('surface')
    = f.number_field :surface, class: 'form-control'
  .form-group
    = f.label :price, t('price')
    = f.text_field :price, class: 'form-control'
  fieldset
    legend = t('owner')
    .form-group
      = f.label :name, t('name')
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :phone, t('phone')
      = f.text_field :phone, class: 'form-control'
    .form-group
      = f.label :email, t('email')
      = f.text_field :email, class: 'form-control'

    = f.hidden_field :lat, value: 0, id: 'latitude_field'
    = f.hidden_field :lng, value: 0, id: 'longitude_field'

  .actions
    = f.submit t('actions.create'), class: 'btn btn-primary'

app/views/reports/_pdf_template.slim
page.cover
  .cover-header
    .cover-inner
      h2.subtitle Marché immobilier
      h1.title  Etude d'estimation 
  .cover-information
    span.label 
      | A la demande de:
      b Bruno B
    span.label 
      | Réalisé par:
      b Mr Bruno BOUCHON 
    span.label 
      | Fait le:
      b jeudi 18 février 2016
page
  header
    == image_tag 'logo.png', :class => "logo"    
    h4.page-title
      strong
        | ANALYSE 
      |DE CONTEXTE CONCURRENTIEL
  == image_tag 'property.png', :class => "property-image"
  
  .pdf-content
    .section-left
      .section-content 
        h5.paragraph_title
          strong
            | Maison
        table.property-table.table       
          tr 
            th = t('address')
            td
              |{{ property.address }}    
          tr 
            th = t('price')
            td 
              |{{ property.price }}
          tr 
            th = t('surface')
            td
              |{{ property.surface }}   
        ng-map center="[{{property.lat}}, {{property.lng}}]" width="200"
         marker position="{{property.lat}}, {{property.lng}}" draggable="true" 
        h5.paragraph_title
          strong
            |Propriétaire
        h6
          |M.
          strong 
            | Francois Durand  
        h6
          |49, rue de la Republique   
        h6
          |7700 Melun   
        h6
          |T.
          strong
            | 06.49.03.34.45
        h6  
          |E.
          strong
            | francois.durand@freemail.com   


    .section-right
      .section-content 
        h5.paragraph_title
          strong
            | Description du bien :
        p 
          | Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        h5.paragraph_title
          strong
            | Description du secteur :
        p 
          | Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.  
        .featured_section
          h6
            strong
              |- Notre méthodologie d’analyse -
          p
            small
              | Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt ex- plicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequun- tur magni dolores eos qui ratione voluptatem sequi nesciunt.
    .clearfix

    footer
      .section-left
        .section_content
          = image_tag 'agent.png', :class => "agent_photo float_left"
          .agent_title
            h5
              strong 
                | David
              |Delacroix
            h6
              | Conseiller Immobilier chez I@D    
      .section-right
        .section-content.agent_contact
          .phone.sprite
          h6
            |06 44 08 79 88
          br
          .email.sprite
          h6
            |david.delacroix@iadfrance.com  
          br  
          .location.sprite
          h6
            | Champigny sur Marne
      .clearfix
      
page
  header
    .page-num 2
    h4.page-title Chart
    div.header-rect
  h2 Line Chart
  div#line-chart-container style="width:700px;height:500px; margin:0 auto"
/* page */
/*   header */
/*     div.page-num 2 */
/*     h4.page-title Charts - Line and Bar */ 
/*     div.header-rect */
/*   h2 Line Chart */
/*   canvas#line-chart width="700" height="450" */ 
/*   br */
/*   br */
/*   h2 Bar Chart */
/*   canvas#bar-chart width="700" height="450" */ 

/* page */
/*   header */
/*     div.page-num 3 */
/*     h4.page-title Charts - Pie and Doughnut */ 
/*     div.header-rect */
/*   h2 Pie Chart */
/*   .box-chart */
/*     canvas#pie-chart width="400" height="400" */ 
/*   br */
/*   br */
/*   h2 Doughnut Chart */
/*   .box-chart */
/*     canvas#dough-chart width="400" height="400" */ 
page
  header
    div.page-num 4
    h4.page-title Similar Houses 
    div.header-rect

  .card-area
    .card ng-repeat="house in property.similar_properties"
      img.card-img-top src="{{ house.photo_url }}"
      .card-block
        h4.card-title
          | {{ house.title }}
        p.card-text 
          | {{ house.price }}
        p.card-text
          | {{ house.surface }}
        p.card-text
          small.text-muted 
            | {{ house.description }}

app/views/reports/competitors.slim
= content_for :head
  = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyDWif-Vrje2gPVDFGFWcUytgJmZxUMQlRU&libraries=places"
  = javascript_include_tag 'vendor/chart.min'
  = javascript_include_tag 'vendor/highchart.min'  
  = javascript_include_tag 'chart_render'
  = javascript_include_tag 'vendor/ng-map.min.js' 
  = javascript_include_tag 'views/properties/related'
  javascript:
    window.report = #{@report}

.content ng-app="app" ng-controller="relatedController"
  // STEP 1
  .step-1 ng-hide="step != 1"
    h4 Search similar properties
    br
    form.form-inline ng-submit="searchRelateds(search)"
      .form-group
        label = t('price') 
        input.form-control type="text" ng-model="report.price" placeholder="Price"
      .form-group
        label = t('surface') 
        input.form-control type="text" ng-model="report.surface" placeholder="Surface"
      .form-group
        label = t('address') 
        input.form-control type="text" ng-model="report.address" placeholder="Address"
      .form-group
        input.btn.btn-primary type="submit" value="#{t('actions.search')}"

  // STEP 2
  .step-2 ng-hide="step != 2"
    h4 Related similar result 
    table.table
      thead.thead-inverse
        tr
          th 
          th = t('image')
          th = t('surface')
          th = t('price')
          th = t('title')
      tbody
        tr ng-repeat="property in relateds"
          td 
            input type="checkbox" ng-change="changeValue(properties[property.id])" ng-model="properties[property.id]" ng-init="properties[property.id] = (properties[property.id] ? properties[property.id] : false);"
          td 
            img.img-rounded ng-src="{{ property.photo_url }}" width="100"
          td
            | {{ property.surface }}
          td
            | {{ property.price }}
          td
            | {{ property.title }}

    button.btn.btn-primary ng-click="saveRelateds()" 
      | Save

  // STEP 3
  .step-3 ng-hide="step != 3"
    h4 Report preview 
    = render partial: 'pdf_template'

  .form-group
    button.btn.btn-primary-outline ng-hide="step == 1" ng-click="back()" 
     | Previous
    button.btn.btn-primary-outline ng-hide="step == 3" ng-click="next()"
     | Next

app/views/reports/edit.slim
javascript:
  window.property = #{@report.html_safe}

.edit-content ng-app="appController" ng-controller="editController" 

  .content-pdf 
    = render 'pdf_template'

  .sidebar
    button.btn.btn-secondary.btn-lg onclick="window.print()"
      = t('actions.print')
    br
    br
    form ng-submit="saveProperty()"
      fieldset.form-group
        label = t('photo') 
        input.form-control type="file" fileread="property.photo.src"
        input.form-control type="hidden" ng-model="property.photo.src"
      fieldset
        label = t('property_type')
        .radio
          label
            input type="radio" value="0" name="property_type" ng-model="property.property_type"/ 
            span = t('house')
        .radio
          label
            input type="radio" value="1" name="property_type" ng-model="property.property_type"/ 
            span = t('flat')
      fieldset.form-group
        label = t('rooms') 
        input.form-control type="number" ng-model="property.rooms"
      fieldset.form-group
        label = t('description') 
        textarea.form-control ng-model="property.description"
      fieldset.form-group
        label = t('rooms') 
        input.form-control type="number" ng-model="property.rooms"
      fieldset.form-group
        label = t('address') 
        input.form-control#address_field type="text" ng-model="property.address"
      fieldset.form-group
        label = t('surface')
        input.form-control type="number" ng-model="property.surface"
      fieldset.form-group 
        label = t('price')
        input.form-control type="text" ng-model="property.price"
      fieldset
        legend = t('owner')
      fieldset.form-group
        label = t('name') 
        input.form-control type="text" ng-model="property.name"
      fieldset.form-group
        label = t('phone') 
        input.form-control type="text" ng-model="property.phone"
      fieldset.form-group
        label = t('email') 
        input.form-control type="text" ng-model="property.email"
      // Latitude and longitude hidden fields
      input type="hidden" ng-model="property.lat"
      input type="hidden" ng-model="property.lng"
      
      input.btn.btn-primary type="submit" value="#{t('actions.save')}"
    br
    br
    br
    br

= content_for :head 
  = javascript_include_tag 'views/directives/file_upload'
  = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyDWif-Vrje2gPVDFGFWcUytgJmZxUMQlRU&libraries=places"
  = javascript_include_tag 'views/properties/edit'
  = javascript_include_tag 'vendor/chart.min'
  = javascript_include_tag 'vendor/highchart.min'  
  = javascript_include_tag 'chart_render'
  = javascript_include_tag 'vendor/ng-map.min'
  = javascript_include_tag 'address_complete'

app/views/reports/index.slim
h2 = t('properties')
br
= link_to t('actions.new_report'), new_report_path, class: 'btn btn-primary'
br
br
nav.navbar.navbar-light.bg-faded
  form.form-inline.pull-xs-right
    label = t('actions.search') 
      | &nbsp;
    input.form-control name="contact_name" type="Text" placeholder="#{t('contact_name')}"
    | &nbsp;
    .form-group.search-date-fields
      label = t('from_date') 
      input.form-control.form-control-sm name="from_date" type="date"
      | &nbsp;
      label = t('to_date')
      input.form-control.form-control-sm name="to_date" type="date"
    | &nbsp;&nbsp;
    input.btn.btn-primary-outline type="Submit" value="#{t('actions.search')}"
table.table.table-striped
  thead
    tr
      th = t('creation_date') 
      th = t('type')
      th = t('description')
      th = t('rooms')
      th = t('address')
      th = t('surface')
      th = t('price')
      th = t('owner')
      th 
  tbody
    - @reports.each do |report|
      tr
        td = report.created_at.strftime('%m/%d/%Y') 
        td = t(report.property_type)
        td = report.description
        td = report.rooms
        td = report.address
        td = report.surface
        td = report.price
        td 
          dl.dl-horizontal
          dt = t('name')
          dd = report.name
          dt = t('phone')
          dd = report.phone
          dt = t('email')
          dd = report.email
        td
          .btn-group.btn-group-sm 
            = link_to t('actions.print')  , report_path(report, print: true), target: '_blank', class: 'btn btn-info-outline' 
            = link_to t('actions.edit')   , edit_report_path(report), class: 'btn btn-primary-outline'
            = link_to t('actions.destroy'), report, method: :delete , data: { confirm: t('confirm_question') }, class: 'btn btn-danger-outline'
= (paginate @reports) if @reports.any?            
br

app/views/reports/new.html.erb
<br>
<%= link_to t('actions.back'), reports_path %>
<br>
<h2><%= t('actions.new_report') %></h2>

<%= render 'form' %>

app/views/reports/show.slim
= content_for :head 
  = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyDWif-Vrje2gPVDFGFWcUytgJmZxUMQlRU&libraries=places"
  = javascript_include_tag 'views/properties/show'
  = javascript_include_tag 'vendor/chart.min'
  = javascript_include_tag 'vendor/highchart.min'
  = javascript_include_tag 'chart_render'
  = javascript_include_tag 'vendor/ng-map.min.js'  

javascript:
  window.property = #{@report.html_safe}

div ng-app="appController" ng-controller="showController"
  = render 'pdf_template'